/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Influencer.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Influencer.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 3.927, 0.622]}>
        <group position={[-0.568, 0.511, 0.667]}>
          <group position={[0.067, 0.169, 0.019]} rotation={[0, -0.458, 0]}>
            <mesh geometry={nodes['l_eyelashes_(1)_1'].geometry} material={materials['Metal Powder Coating 001 Black 50cm']} rotation={[0.494, 0.119, -0.064]} />
          </group>
          <group position={[-0.067, 0.169, -0.019]} rotation={[0, -0.713, 0]}>
            <mesh geometry={nodes['l_eyelashes_(2)_1'].geometry} material={materials['Metal Powder Coating 001 Black 50cm']} rotation={[0.494, 0.119, -0.064]} />
          </group>
          <mesh geometry={nodes.l_eye_1.geometry} material={materials['Metal Powder Coating 001 Black 50cm']} position={[0.004, -0.169, 0.005]} rotation={[0, -0.456, 0]} />
        </group>
        <group position={[0.572, 0.511, 0.689]}>
          <group position={[-0.063, 0.169, 0.03]}>
            <mesh geometry={nodes['r_eyelashes_(1)_1'].geometry} material={materials['Metal Powder Coating 001 Black 50cm']} rotation={[0.494, 0.119, -0.064]} />
          </group>
          <group position={[0.063, 0.169, -0.03]} rotation={[0, 0.255, 0]}>
            <mesh geometry={nodes['r_eyelashes_(2)_1'].geometry} material={materials['Metal Powder Coating 001 Black 50cm']} rotation={[0.494, 0.119, -0.064]} />
          </group>
          <mesh geometry={nodes.r_eye_1.geometry} material={materials['Metal Powder Coating 001 Black 50cm']} position={[-0.008, -0.169, -0.008]} rotation={[0, 0.33, 0]} />
        </group>
        <group position={[0.029, -0.681, -0.794]}>
          <mesh geometry={nodes['body-Pottery_Rough_005_LightBlueGrey_20cm'].geometry} material={materials['Pottery Rough 005 LightBlueGrey 20cm']} />
          <mesh geometry={nodes['body-Pottery_Rough_005_LightBlueGrey_20cm_1'].geometry} material={materials['Pottery Rough 005 LightBlueGrey 20cm']} />
          <mesh geometry={nodes['body-Pottery_Rough_005_LightBlueGrey_20cm_2'].geometry} material={materials['Pottery Rough 005 LightBlueGrey 20cm']} />
        </group>
        <mesh geometry={nodes.mouth.geometry} material={materials['Carpaint Matte 001 White 25cm']} position={[0, -0.103, 0.794]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Influencer.glb')
